---
title: "Reproduction_Manuscript2"
author: "Yue"
output:
  word_document: default
  pdf_document:
    fig_caption: yes
---


## Introduction

(In general, what is the idea?)
To describe how context could affect the accuracy of time estimation in human. 

(time perception of human can be precise, but easily be distorted)
On the one hand, humans are surprisingly good at time estimation (Image this, as a driver in a formula 1 race, the requirement for a precise control could be under the speed up to 300km/h, and when dancing, to perform a perfect harmony with your partner, the control for the muscles of whole body can be so complex but accurate, those all involve highly control of sense of time)
On the other hand, time can also be easily distorted, the feeling for two minutes is definitely different when you are in the middle of a test or you are on the beach in Spain.

(widely accepted law in describing accuracy of time perception)
Weber’s law has been widely accepted in describing the sensitivity of measuring perceptive magnitude. According to the law, the variable of estimation is proportional to the magnitude of the stimuli, where the just noticeable difference is stated. Dubbed the ‘scalar property’ (Gibbon, Meck) within the field of interval timing, this law predicts the variation of the estimated intervals should increase linearly with the interval value . So by calculating the standard deviation in estimates divided by the corresponding interval, termed coefficient of variance(CV), this measurement should remain constant across a range of intervals within single mechanism of time perception. 

(previous findings: against constancy of CV)
During the past two decades, several studies have reported different kinds of distributions of CVs against intervals but constant(,,,,), where a systematic violation of scalar property was stated. 
(In 2009, by employing an interval reproduction task, lewis and Miall (2009) discovered a continuous logarithmic decrease in CV in a wide time range(68ms to 16.7min), where the break points of distinct clock mechanisms were carefully examined ) . 

(We are against the conclusion that cv decrees => violation of weber’s law )
However, we doubt about the conclusion that the violation of the fundamental percept of timing was found, since temporal context plays an important role in affecting the precision of perception but rather by violating the general law where the standard deviation scales with the temporal intervals.    

(Why Bayesian Model in explaining the contextual effect on the precision of perception.)
Bayesian’s rule provided a integrated framework for temporal perception that combined context bias and perceptual likelihood into one statistical inference(Zhuanghua Shi, David Burr, Jazayeri). 

According to this model, the estimated duration S, which quantified as the posterior probability P(D|S), is determined by two sources of information: The likelihood function P(S|D) that quantifies the statistics of sample intervals consistent with the tested intervals, and the prior probability  distribution function P(S) where the external context was involved that observers may encounter. 
(need some figure here to illustrate the whole model and how to calculate the relations between the variations)

 P(D|S)  P(S|D) P(S)

(previous study: bayesian model in explaining temporal bias)
In 2010, by reproducing time intervals from humans in subsecond-to-second range, Jazayeri and Shadlen suggested  a Bayesian observer associated with the Byes least-squares(BLS) could account for the temporal bias where subjects’s estimations were dependent on both the sample intervals and the prior distribution. In this model, when the likelihood and the prior are independent Gaussians, that is P(S|D)~N(us, ds), P(D)~N(up, dp), the variance of  optimal estimate is 

dp^2 *ds^2 / (dp^2 + ds^2) 

which guarantees a minimum variance among all possible linear weighted combinations between the sensory estimate and the prior.()

(why CV would decrease using the model)
When applying this model into reproduction task, we could calculate the posterior estimation based on this model.
For the prior probability, a same temporal context shares one variance dp for all the tested intervals. 
For each given external duration, Di is corresponding to a variance di from each likelihood function. According to the scalar property, di is proportional to the sample interval Di. 

di  k* Di.  (Here we didn’t take motor noise into consideration, only the bias from the perceptual estimations)

Now when we try to predict the CVs of the estimations using this model. According to the definition, CV is the ratio between the standard deviation of the data points and the value of each interval. In this case, for each data point, 

CVi = dpi / Di

By taking equations () and () into calculation, 

Cvi  1/Di (CV^2 = dp/ (Di^2 + dp^2/k^2))

As have been demonstrated by Jazayeri, the BLS model fits perfectly for the data from temporal reproduction task. Using the same model for prediction in temporal reproduction task, when taking the temporal context into consideration, CVs would decrease as the intervals increase. 
(So previous studies that suggesting a systematical violation of scalar property is not convincing)

[Using the model, central tendency effect has been well explained where an optimal strategy was adopted in improving the accuracy while tasking.(percussionist) ]


(what we did: distinguish conditions/using bayesian model to explain the decrease/)

In order to demonstrate this prediction, we conducted four experiments within two modalities: visual and auditory, respectively. For each modality, we tested the same sample intervals for a temporal reproduction task in two conditions: Mix condition and Block condition. Under the Mix condition, all the intervals were mixed together and tested within one block, while under the Block condition, all the intervals were divided into three groups: short, medium and long, and tested separately. 

(what we show, results)
By dividing sample intervals into two conditions, we anticipated the condition difference where CVs show different tendencies against intervals. We calculated the mean CVs for each tested interval, simple logarithmic regressions were fit for data from each experiment. A condition difference was significantly illustrated where under Mix condition from both modalities, a decreasing tendency was found while under Block condition, 

## Results

### Reproduction
#### Mean Estimation

#### Standard Deviations

### Reproduction Error

### Production



